### ISSUE TITLE
Misc bug fixes (commenting-on-posts)

### ISSUE THREAD

**Issue by mayankshouche** [benjamin-fa/ai-portal#28]
~~1. collapsible comment box (see reddit desktop) (@mayankshouche)~~

![image](https://user-images.githubusercontent.com/43075711/113372703-de29eb80-932e-11eb-9134-88c41033bd49.png)

~~2. infinite loop of requests to /resource/... on resource pages, has to do with the useEffect
    * The 'fetchResource' function makes the dependencies of useEffect Hook (at line 73) change on every render. To fix this, wrap the 'fetchResource' definition into its own useCallback() Hook~~

~~3. make replies reload page state so they show up (@stephen8chang)
    * right now, once submitting a reply/comment page does not repaint with the new comment
    * some replies not rendering even though comment count correct~~

~~4. make comment/ api routes send back a 200 when successful (@rafaykhurram)~~
 
~~5. error checking for /comment/.* api responses (@rafaykhurram)
    * api response could fail - make sure to display error on frontend if this happens~~

~~6. firewall access denied errors in server output (@normanwang1234)

![image](https://user-images.githubusercontent.com/43075711/113378491-c6596400-933c-11eb-8585-f318d3dfba21.png)~~

**Comment by benjamin-fa** [comment]
In response to the third bug on loading replies, it took about a minute and 15 seconds for all the comments to load on the "Scale 3D Sensor Fusion, Scale Image, Scale Video, Scale Text, and Scale Document API" resource for me. It started off only rendering 8, then there were 13, and then there were 29 total comments (though the page numerically indicates 12 replies). Not sure what's going on there

**Comment by stephen8chang** [comment]
Bug number 3 on this issue is fixed

**Comment by rafaykhurram** [comment]
Bugs #4 and #5 on this issue are fixed.

**Comment by mayankshouche** [comment]
Opened PR for issue 1 since it could be a breaking change: #30

**Comment by mayankshouche** [comment]
Bug 6 fixed through other changes
