### ISSUE TITLE
Search Bar for Discussion Forum Posts (discussion-forum)

### ISSUE THREAD

**Issue by stephen8chang** [benjamin-fa/ai-portal#38]

**Comment by rafaykhurram** [comment]
https://github.com/benjamin-fa/ai-portal/commit/45b2a5620e17a337eee7c41bede55de573ad2e87

**Comment by rafaykhurram** [comment]
Search works fine now. Issue was search was looking through non-string parameters from the mongoose database. It searches through the header, the text, the tags, and associate roles from the database. It does not search through the user's name since that's not a string parameter .
