### ISSUE TITLE
Discussion Forum Post Page (discussion-forum)

### ISSUE THREAD

**Issue by stephen8chang** [benjamin-fa/ai-portal#41]
EDIT 9/15/2021:
- "Go back to discussion forum page" component (DONE)
- displaying posts from mongodb database (DONE)
- displaying page + comments after clicking a discussion (DONE)
- display post after submitting new post, needs bug fix - @normanwang1234 (DONE)
- add upvotes for discussion posts - @stephen8chang (DONE)
- fix UI on discussion post page - @yashdhaduti 
- BUG: comment count on each discussion forum post not accurate - 

See designs [here](https://www.figma.com/file/jQbuNwmWZvFzmUblAgI78m/Discussion-Forum-UI?node-id=0%3A1)

**Comment by rafaykhurram** [comment]
Displaying posts from MongoDB database is already done. @benjamin-fa @normanwang1234 How should we split up the other 3 parts?

**Comment by benjamin-fa** [comment]
@rafaykhurram You can just pick one of the 3 parts to do
