### ISSUE TITLE
'make an account to pin' notification showing up incorrectly

### ISSUE THREAD

**Issue by mayankshouche** [benjamin-fa/ai-portal#45]
When not logged in and visiting a resource page, I get the following notification after the page loads (before I had a chance to click anything, including the pin icon).

![image](https://user-images.githubusercontent.com/43075711/117395267-38cdde80-aebd-11eb-94f5-e0f59d49dcfb.png)

**Comment by normanwang1234** [comment]
Looks fixed to me. Going to close for now.
